### ISSUE TITLE
样式有问题，阅读性不好，你用的什么浏览器

### ISSUE THREAD

**Issue by dpheyu** [xueqiu/rdr#11]
试了下，top 100 largest keys显示不友好。

**Comment by dpheyu** [comment]
![507184023](https://user-images.githubusercontent.com/16263327/39698370-270a4454-5227-11e8-924e-48a79090494b.png)

**Comment by dpheyu** [comment]
![_20180507184830](https://user-images.githubusercontent.com/16263327/39698405-467adb50-5227-11e8-8edf-fb9733cce218.png)

**Comment by dongmx** [comment]
chrome , 是不是下面有key特别长？
