### ISSUE TITLE
怎么更改报表中统计使用的前缀符号啊？

### ISSUE THREAD

**Issue by 401825317** [xueqiu/rdr#17]
如题，我的不知道我的报表中使用的前缀符号是啥。怎么更改啊 我们系统中用的是 "_"

**Comment by 401825317** [comment]
@pawa @mengxy @zzlang @zhoumin007

**Comment by dongmx** [comment]
默认支持了常见的分隔符、比如 _ ; : , 等等，可以直接使用一下看看效果
