### ISSUE TITLE
performance inquire

### ISSUE THREAD

**Issue by bibabolynn** [xueqiu/rdr#18]
I read from this website http://www.infoq.com/cn/articles/analysis-redis that your performance is times better than redis-rdb-tools. I'm wondering , do you have any statistics compare these two. How is performance with 10 millions keys or more. And how can I use it but print results in files instead show on a website 

@dongmx  hope hear from you soon.

**Comment by dongmx** [comment]
It depends on keys's type and data size. Usually it takes dozens of seconds in my experience. You can have a try. 
Sure you can print results in files. But it need some small changes. If you are  familiar with golang, it should be easy.
