### ISSUE TITLE
If i extract it as a library seperate from main.go, would u accept the PR?

### ISSUE THREAD

**Issue by YongHaoWu** [xueqiu/rdr#22]
Or I will just fork it for myself

**Comment by dongmx** [comment]
Basically, I suggest you fork it. Cloud you tell me more about the reason for changing it to a library?

**Comment by YongHaoWu** [comment]
@dongmx Thanks for your reply. I needs to use it as a function in my project instead of using binary.

**Comment by dongmx** [comment]
@YongHaoWu Looks like a personal need. Most users want out of the box. Take it as a binary may help more people.

**Comment by YongHaoWu** [comment]
@dongmx Take a look on my PR  https://github.com/xueqiu/rdr/pull/23. Seperate it as library doesn't conflict with binary.

**Comment by dongmx** [comment]
@YongHaoWu LGTM if you change imports from `YongHaoWu/rdr` to `xueqiu/rdr`

**Comment by YongHaoWu** [comment]
@dongmx Will create a new PR.
