### ISSUE TITLE
rdr show只支持本地监听地址么？

### ISSUE THREAD

**Issue by thinkboy** [xueqiu/rdr#3]
./rdr show -p 8080 *.rdb  只支持本地监听地址么？我在测试机上分析，怎么用自己的机器访问过去呢。

**Comment by dongmx** [comment]
不是只支持本地访问，如果网络可达的话，直接在浏览器输入 测试机ip:8080 就可以访问了

**Comment by dongmx** [comment]
可能输出的提示会让人感觉有些疑惑，我后续变更一下

**Comment by thinkboy** [comment]
soga 多谢
