### ISSUE TITLE
Support for RDB version 7

### ISSUE THREAD

**Issue by omame** [xueqiu/rdr#4]
When I try to parse an RDB file from Redis 3.2.5 I get this error:

```
start parsing...
decode rdbfile err: rdb: invalid RDB version number 7
```

Looking at the vendored version of `cupcake/rdb` it does indeed seem like it's unsupported: https://github.com/xueqiu/rdr/blob/master/vendor/github.com/cupcake/rdb/decoder.go#L588

But the version 7 support landed in upstream 6 months ago: https://github.com/cupcake/rdb/pull/6

So it does seem like you need to re-vendor and distribute a new build.

**Comment by dongmx** [comment]
Got it, thank you.

**Comment by dongmx** [comment]
I've update dependency and binary file to support rdb v7. Thank for your report 👍
