### ISSUE TITLE
是否有windows 版本的release

### ISSUE THREAD

**Issue by 18965824402** [xueqiu/rdr#5]
是否有windows 版本的release

**Comment by dongmx** [comment]
可以有，我周末加一下

**Comment by 18965824402** [comment]
找不到链接  ？

**Comment by dongmx** [comment]
想了一下，感觉不太科学吧，redis 官方也没有 windows 版本啊

**Comment by SuperDubbo** [comment]
+1

**Comment by SuperDubbo** [comment]
redis有windows的啊

**Comment by SuperDubbo** [comment]
redis-rdb-tools在windows上面也可以玩啊

**Comment by SuperDubbo** [comment]
哈哈，源代码下载下来，自己编译成功，window一样跑

**Comment by SuperDubbo** [comment]
已放到github，如有需要可下载，https://github.com/SuperDubbo/rdr/releases

**Comment by SuperDubbo** [comment]
@dongmx 建议放出windows官方版本供大家使用吧

**Comment by SuperDubbo** [comment]
@dongmx 已解决，我开始构建的win32版本，造成内存溢出问题，谢谢
