### ISSUE TITLE
使用教程能否详细一些，谢谢！

### ISSUE THREAD

**Issue by dufyun** [xueqiu/rdr#7]
你好，刚学习redis，看这个教程有点难，有详细的使用说明吗？

**Comment by dongmx** [comment]
这个小工具非常简单，一共就俩命令，一个是 show，一个是 keys，第一个会生成一个报表的网页，第二个会把 rdb 里所有的 key 都输出出来，试试就知道了。
命令就是 ./rdr show xxx.rdb 和 ./rdr keys xxx.rdb

后续我看看再更新下文档
